return {
  -- "saghen/blink.pairs",
  -- version = "*", -- (recommended) only required with prebuilt binaries
  -- lazy = "BufReadPre",
  --
  -- -- download prebuilt binaries from github releases
  -- dependencies = "saghen/blink.download",
  -- -- OR build from source
  -- -- build = "cargo build --release",
  -- -- OR build from source with nix
  -- -- build = "nix build .#build-plugin",
  --
  -- --- @module 'blink.pairs'
  -- --- @type blink.pairs.Config
  -- opts = {
  --   mappings = {
  --     -- you can call require("blink.pairs.mappings").enable() and require("blink.pairs.mappings").disable() to enable/disable mappings at runtime
  --     enabled = true,
  --     -- cmdline = true,
  --     disabled_filetypes = {},
  --     -- see the defaults: https://github.com/Saghen/blink.pairs/blob/main/lua/blink/pairs/config/mappings.lua#L10
  --     pairs = {},
  --   },
  --   ---@diagnostic disable-next-line: missing-fields
  --   highlights = {
  --     enabled = true,
  --     groups = {},
  --     matchparen = {
  --       enabled = true,
  --       group = "MatchParen",
  --     },
  --   },
  --   debug = false,
  -- },
}
