---@class LazyPlugin
return {
  -- "ojroques/nvim-osc52",
  -- lazy = false,
  -- enabled = os.getenv("TMUX") ~= 0,
  -- config = function()
  --   require("osc52").setup({
  --     max_length = 0, -- Maximum length of selection (0 for no limit)
  --     silent = true, -- Disable message on successful copy
  --     trim = false, -- Trim surrounding whitespaces before copy
  --     tmux_passthrough = true,
  --   })
  --
  --   local function copy(lines, _)
  --     require("osc52").copy(table.concat(lines, "\n"))
  --   end
  --
  --   local function paste()
  --     return { vim.fn.split(vim.fn.getreg(""), "\n"), vim.fn.getregtype("") }
  --   end
  --
  --   vim.g.clipboard = {
  --     name = "POSC 52",
  --     copy = { ["+"] = copy, ['"'] = copy, ["*"] = copy },
  --     paste = { ["+"] = paste, ['"'] = paste, ["*"] = paste },
  --   }
  -- end,
}
