-- ---@class LazyPlugin
return {
  --   "zbirenbaum/copilot.lua",
  --   commit = "92e08cd472653beaece28ad9c8508a851a613358",
  --   cmd = { "Copilot" },
  --   event = { "InsertEnter" },
  --   opts = {
  --     panel = {
  --       enabled = false,
  --     },
  --     suggestion = {
  --       enabled = false,
  --       auto_trigger = false,
  --     },
  --     -- filetypes = {
  --     --   yaml = false,
  --     --   markdown = false,
  --     --   help = false,
  --     --   gitcommit = false,
  --     --   gitrebase = false,
  --     --   hgcommit = false,
  --     --   svn = false,
  --     --   cvs = false,
  --     --   ["."] = false,
  --     -- },
  --     -- copilot_node_command = "node", -- Node.js version must be > 18.x
  --     -- server_opts_overrides = {},
  --   },
}
