---@module "vim.lsp.client"
---@class vim.lsp.ClientConfig
-- return {
--   filetypes = {
--     "javascript",
--     "javascriptreact",
--     "javascript.jsx",
--     "typescript",
--     "typescriptreact",
--     "typescript.jsx",
--     "vue",
--   },
--   -- init_options = {
--   --   plugins = {
--   --     {
--   --       name = "@vue/typescript-plugin",
--   --       location = vim.fn.expand("$MASON/packages")
--   --         .. "/vue-language-server/node_modules/@vue/language-server",
--   --       languages = { "vue" },
--   --       configNamespace = "typescript",
--   --     },
--   --   },
--   -- },
-- }
