vim.diagnostic.config { update_in_insert = true }
local bufnr = vim.api.nvim_get_current_buf()
local map = vim.keymap.set

map("n", "<leader>ca", function()
  vim.cmd.RustLsp("codeAction")
  -- or vim.lsp.buf.codeAction() if you don't want grouping.
end, { silent = true, buffer = bufnr })
map("n", "K", function()
  vim.cmd.RustLsp { "hover", "actions" }
end, { silent = true, buffer = bufnr })
map("n", "<leader>rr", function()
  vim.cmd.RustLsp("run")
end, { silent = true, buffer = bufnr })
map("n", "<leader>rR", function()
  vim.cmd.RustLsp("runnables")
end, { silent = true, buffer = bufnr })
map("n", "<leader>dd", function()
  vim.cmd.RustLsp("debuggables")
end, { silent = true, buffer = bufnr })
map("n", "<leader>rt", function()
  vim.cmd.RustLsp("testables")
end, { silent = true, buffer = bufnr })
map("n", "<leader>oc", function()
  vim.cmd.RustLsp("openCargo")
end, { silent = true, buffer = bufnr })
map("n", "<leader>od", function()
  vim.cmd.RustLsp("openDocs")
end, { silent = true, buffer = bufnr })
map("n", "<leader>jd", function()
  vim.cmd.RustLsp("relatedDiagnostics")
end, { silent = true, buffer = bufnr })
map("n", "<leader>ee", function()
  vim.cmd.RustLsp("explainError")
end, { silent = true, buffer = bufnr })
